version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - .:/netology
    tty: true
    environment:
      - TIME_BREAK=10000
    ports:
      - 8080:8080
    depends_on:
      - db
    command: "python3 ./script.py"
      
  db:
    build: 
      context: ./database
      dockerfile: ./Dockerfile
    ports:
      - 5432:5432
