version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - .:/netology
    tty: true
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    build: 
      context: ./database
      dockerfile: ./Dockerfile
    ports:
      - 5432:5432
