version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - .:/netology
    tty: true
    environment:
      - EXACT_TIME=00:27
      - HOSTNAME=db
      - USERNAME=postgres
      - PASSWORD=postgres
      - DBNAME=netology
    ports:
      - 8080:8080
    depends_on:
      - db
    command: "python3 ./script.py"
      
  db:
    build: 
      context: ./database
      dockerfile: ./Dockerfile
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=netology
    ports:
      - 5432:5432
